# Site settings
title: A blog about shaojie
description: A blog about shaojie
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 少 桀
user_description: 2016年 毕业于电子神技大学 加入上汽技术中心 后离职加入七牛云 资深图像处理工程师 深度学习爱好者
user_title: Software Developer
email: logo_yongjie@163.com
twitter_username: babybabyloveusomach
github_username:  asjgit
gplus_username:  好日子

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
